### ISSUE TITLE
Visual feedback from Frederik

### ISSUE THREAD

**Issue by wallymathieu** [byggkostnad/byggkostnad.github.io#7]
- the left hand - outline of a large letter - leaves a tiny blue triangle inside ( 32" monitor )

**Comment by fTops** [comment]
At first I wasn't sure what that meant but he probably means what you see on the left here: http://quirktools.com/screenfly/#u=http%3A//byggkostnad.com&w=2560&h=1440

Makes sense as I made the letters reposition themselves for various lower resolutions than 1080p, but not for higher yet. We'll do for up to 4K or something.

**Comment by fTops** [comment]
I repositioned them for various widths.

How it looks for some common high resolutions up to 4K:

http://quirktools.com/screenfly/#u=http%3A//byggkostnad.com&w=1920&h=1080
http://quirktools.com/screenfly/#u=http%3A//byggkostnad.com&w=2560&h=1440
http://quirktools.com/screenfly/#u=http%3A//byggkostnad.com&w=3200&h=1800
http://quirktools.com/screenfly/#u=http%3A//byggkostnad.com&w=3840&h=2160
